name: laminas_dev

type: php:7.3

size: S

disk: 256

build:
  flavor: none

dependencies:
  php:
    "hirak/prestissimo": "^0.3.9"

mounts:
  'data/cache':
    source: local
    source_path: data/cache

hooks:
  build: |
    set -e
    echo "Installing platform.sh CLI"
    curl -sS https://platform.sh/cli/installer | php
    echo "- Setting up configuration"
    rm -f config/development.config.php config/autoload/*.local.php
    mv config/autoload/local.php.dist config/autoload/local.php
    echo "- Installing application dependencies"
    composer install --no-ansi --no-dev --no-interaction --no-scripts --no-plugins --optimize-autoloader
  deploy: |
    rm -f data/cache/config-cache.php

crons:
    snapshot:
        # Take a snapshot automatically every night at 3 am (UTC).
        spec: '0 3 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform snapshot:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 8 am (UTC) on the 14th and 28th of every month.
        spec: '0 8 14,28 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi

web:
  commands:
    start: 'php vendor/bin/mezzio-swoole start'
  upstream:
    socket_family: tcp
    protocol: http
  locations:
    '/':
      root: 'public'
      passthru: '/index.php'
      index:
        - index.html
      scripts: true
      allow: true
      request_buffering:
        enabled: true
        max_request_size: 25m
