version: "3"
services:

  web:
    image: phpswoole/swoole:4.8-php7.4-alpine
    env_file:
      - .env
    entrypoint: ['php', 'vendor/bin/mezzio-swoole', 'start']
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
